name: Build and Test

on: [push, workflow_dispatch]

jobs:
  
  # Build main artifacts
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: mingw32, env: i686 }

    steps:
      # Output run ID - in case we need it to release the artifacts. 
      # For information, also dump entire GitHub context.
      - name: "Current run ID ${{github.run_id}}: Dump Context"
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo "Run ID: ${{github.run_id}}"
          echo ${env:GITHUB_CONTEXT}

      # Checkout source tree
      - name: Checkout
        uses: actions/checkout@v2

      # Setup MSYS2
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
             mingw-w64-${{matrix.env}}-toolchain
             mingw-w64-${{matrix.env}}-nsis
             mingw-w64-${{matrix.env}}-icu
          
      # Build
      - name: Build SQLite ODBC
        shell: msys2 {0}
        run: |
          cd build
          ./build/mingw-build.sh
        
        
