name: Build and Test

on: [push, workflow_dispatch]

jobs:
  
  # Build main artifacts
  build:
    runs-on: windows-latest

    steps:
      # Output run ID - in case we need it to release the artifacts. 
      # For information, also dump entire GitHub context.
      - name: "Current run ID ${{github.run_id}}: Dump Context"
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        run: |
          echo "Run ID: ${{github.run_id}}"
          echo ${env:GITHUB_CONTEXT}

      # Checkout source tree
      - name: Checkout
        uses: actions/checkout@v2

      # Update MSYS2
      - name: Update 
        run: |
          C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
        
